### PR TITLE
Changes to SquaresWithThreeSides.java

### PR DESCRIPTION
**Pull request by r-fortanely**
Updated array of side lengths to omit whitespace, code kind of ugly. Can you explain how you compared the triangle lengths? Answer is 862. :)

### CODE REVIEW

**Comment by BannanaMonarch** [comment]
I didn't even know there was a request open

**Comment by BannanaMonarch** [comment]
GitHub is weird

**Comment by r-fortanely** [comment]
Oh, that's fine.  I just looked over it and messed with it until it worked, haha.

**Comment by BannanaMonarch** [comment]
It cycles through all side length combinations using modulus,
a%3 + b%3 <= c%3
where the loop sets a->b, b->c, c->a until all combinations are exhausted.
because they are commutative, the middle case
a%3 + c%3 = b%3
isn't encountered.

**Comment by r-fortanely** [comment]
Oh, my question was over your old solution

**Comment by r-fortanely** [comment]
No, I understand

**Comment by r-fortanely** [comment]
That technique with the modulus is really clever

**Comment by r-fortanely** [comment]
I like it

**Pull request closed without merging**
